# Generated by Django 4.2.11 on 2024-04-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('author', models.TextField(verbose_name='Автор')),
                ('abstract', models.TextField(verbose_name='Аннотация')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('link', models.TextField(verbose_name='Ссылка на источник')),
            ],
        ),
    ]
